# Generated by Django 4.2.4 on 2023-09-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_rename_teacher_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
    ]
